### ISSUE TITLE
Questions to be solved by lecturer

### ISSUE THREAD

**Issue by AprilV** [wsgdrfz/VideoAnalytics-MachineLearning#6]
Questions to be solved by lecturer:

- Training and Testing data: When we use Raw pixel + SVM + Cross Validation, it is too slow to move forward. Is there any way to accelerate or can we use part of the data?

- Dimensionality reduction: Does it have to be combined with every feature? So there will be: PCA+Raw(15360) & PCA+HOG(7524) & PCA+Edge(15360) & LDA+Raw & LDA+HOG & LDA+Edge plus each original features. In total it will be 9 features to compare. A little much...

- Parameter tuning: What we think about now are following:
    - the value of k in kNN, from 3 to 11
    - the parameters in SVM, which only include svmkernel??
    - the mask B1&B2 in Edge extraction

     Are these enough?

- Evaluation: 
    - Recognition rate = Accuracy?
    - Type I and II errors, sensitivity, precision.... contains how many? Is it okay to show Precision&Recall and Sensitivity&Specificity?

**Comment by wsgdrfz** [comment]
Detection implementation
- Horizontal and vertical scan: What's the difference between them?
- Multi-scale: what size is the window？ 160*96 and then?

Performance
- Reflection. Spotting failures: ??

**Comment by wsgdrfz** [comment]
- Horizontal and vertical scan: just use one, no matter the order of horizontal or vertical
- Multi-scale: size: 160*96,1/2 and double
